### ISSUE TITLE
Add User-Agent header identification string 

### ISSUE THREAD

**Issue by githubrsys** [Ecodev/newsletter#100]
## Solution

Add a user-agent header identification string with a dynamic setup from ext_conf_template.txt

## Problem

The internal crawler (which runs on overview tab in background and analyzes the page) does not identify itself against the webserver. As soon as you avoid anonymous Agent access with htaccess the crawler fails.

**Comment by PowerKiKi** [comment]
Why would anonymous user agent be blocked ? and what user agent string would work for you ?

**Comment by githubrsys** [comment]
Because I prevent with several techniques the scraping of the site. The User-Agent User-Agent: TYPO3_ext_Newsletter/1.0 (whatever) would be nice as Default but setable via constant respective ext_config

**Comment by PowerKiKi** [comment]
I was going to ask why not spoofing existing user-agent. But after reading a bit of documentation I realized that it could be considerate "impolite", and it would only perpetuate the poor practice of agent sniffing. So ok, for a specific user-agent. Would you be aware of any other user-agent string in TYPO3 world ? from another extension perhaps ? so that we could follow a pre-existing convention ?

Also IMHO configuration would add unnecessary complexity for the code and for the users of the extension.

**Comment by githubrsys** [comment]
TBH: Never heard about any default  but TYPO3_extKey seems to me quite obvious.

Cheers

**Comment by PowerKiKi** [comment]
Could you try the develop branch, specifically 981542c, and let me know if it solves your issue, please ?

**Comment by githubrsys** [comment]
Just switched to develop but theres a composer version mismatch. Caches were cleared. So could not test.

````
Version number in composer manifest of package "newsletter" is missing or invalid

Backtrace:

#0 /var/www/web12/html/t3_live/typo3conf/ext/newsletter/Classes/Tools.php(386): TYPO3\CMS\Core\Utility\ExtensionManagementUtility::getExtensionVersion('newsletter') 
#1 /var/www/web12/html/t3_live/typo3conf/ext/newsletter/Classes/Tools.php(399): Ecodev\Newsletter\Tools::getUserAgent() 
#2 /var/www/web12/html/t3_live/typo3conf/ext/newsletter/Classes/Utility/Validator.php(71): Ecodev\Newsletter\Tools::getUrl('http://haas-sem...') 
#3 /var/www/web12/html/t3_live/typo3conf/ext/newsletter/Classes/Utility/Validator.php(97): Ecodev\Newsletter\Utility\Validator->getURL('http://haas-sem...') 
#4 /var/www/web12/html/t3_live/typo3conf/ext/newsletter/Classes/Domain/Model/Newsletter.php(913): Ecodev\Newsletter\Utility\Validator->validate(Object(Ecodev\Newsletter\Domain\Model\Newsletter), NULL) 
#5 /var/www/web12/html/t3_live/TYPO3.CMS1/typo3/sysext/extbase/Classes/Reflection/ObjectAccess.php(123): Ecodev\Newsletter\Domain\Model\Newsletter->getValidatedContent() 
#6 /var/www/web12/html/t3_live/TYPO3.CMS1/typo3/sysext/extbase/Classes/Reflection/ObjectAccess.php(61): TYPO3\CMS\Extbase\Reflection\ObjectAccess::getPropertyInternal(Object(Ecodev\Newsletter\Domain\Model\Newsletter), 'validatedConten...', false, true) 
#7 /var/www/web12/html/t3_live/typo3conf/ext/newsletter/Classes/MVC/View/JsonView.php(249): TYPO3\CMS\Extbase\Reflection\ObjectAccess::getProperty(Object(Ecodev\Newsletter\Domain\Model\Newsletter), 'validatedConten...') 
#8 /var/www/web12/html/t3_live/typo3conf/ext/newsletter/Classes/MVC/View/JsonView.php(213): Ecodev\Newsletter\MVC\View\JsonView->transformObject(Object(Ecodev\Newsletter\Domain\Model\Newsletter), Array) 
#9 /var/www/web12/html/t3_live/typo3conf/ext/newsletter/Classes/MVC/View/JsonView.php(207): Ecodev\Newsletter\MVC\View\JsonView->transformValue(Object(Ecodev\Newsletter\Domain\Model\Newsletter), Array) 
#10 /var/www/web12/html/t3_live/typo3conf/ext/newsletter/Classes/MVC/View/JsonView.php(181): Ecodev\Newsletter\MVC\View\JsonView->transformValue(Array, Array) 
#11 /var/www/web12/html/t3_live/typo3conf/ext/newsletter/Classes/MVC/View/ExtDirectView.php(43): Ecodev\Newsletter\MVC\View\JsonView->renderArray() 
#12 /var/www/web12/html/t3_live/TYPO3.CMS1/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php(327): Ecodev\Newsletter\MVC\View\ExtDirectView->render() 
#13 /var/www/web12/html/t3_live/TYPO3.CMS1/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php(157): TYPO3\CMS\Extbase\Mvc\Controller\ActionController->callActionMethod()
#14 /var/www/web12/html/t3_live/TYPO3.CMS1/typo3/sysext/extbase/Classes/Mvc/Dispatcher.php(69): TYPO3\CMS\Extbase\Mvc\Controller\ActionController->processRequest(Object(TYPO3\CMS\Extbase\Mvc\Web\Request), Object(Ecodev\Newsletter\MVC\ExtDirect\TransactionResponse)) 
#15 /var/www/web12/html/t3_live/typo3conf/ext/newsletter/Classes/MVC/ExtDirect/RequestHandler.php(112): TYPO3\CMS\Extbase\Mvc\Dispatcher->dispatch(Object(TYPO3\CMS\Extbase\Mvc\Web\Request), Object(Ecodev\Newsletter\MVC\ExtDirect\TransactionResponse)) 
#16 /var/www/web12/html/t3_live/TYPO3.CMS1/typo3/sysext/extbase/Classes/Core/Bootstrap.php(195): Ecodev\Newsletter\MVC\ExtDirect\RequestHandler->handleRequest() 
#17 /var/www/web12/html/t3_live/TYPO3.CMS1/typo3/sysext/extbase/Classes/Core/Bootstrap.php(184): TYPO3\CMS\Extbase\Core\Bootstrap->handleRequest() 
#18 /var/www/web12/html/t3_live/TYPO3.CMS1/typo3/sysext/extbase/Classes/Core/ModuleRunner.php(68): TYPO3\CMS\Extbase\Core\Bootstrap->run('', Array) 
#19 /var/www/web12/html/t3_live/TYPO3.CMS1/typo3/mod.php(38): TYPO3\CMS\Extbase\Core\ModuleRunner->callModule('web_NewsletterT...') 
#20 {main}
````

**Comment by PowerKiKi** [comment]
It seems you are on TYPO3 lower than 7.4, I fixed that and now Travis builds succeed. Could you please try again with da5aa90, please ?

**Comment by githubrsys** [comment]
### Seems to work

````
93.95.xx.xx - - [07/Jan/2016:08:15:15 +0100] "GET /index.php?id=5296&type=9101 HTTP/1.1" 200 26887 "-" "TYPO3/6.2.17 Newsletter/2.6.0 (https://github.com/Ecodev/newsletter)"
````

:+1: 

Thanks for your effort. Cheers!
