### ISSUE TITLE
Could not analyse class:Ecodev\News\Controller\NewsController

### ISSUE THREAD

**Issue by githubrsys** [Ecodev/newsletter#53]
I got the point. As soon ext:news and ext:newsletter is installed I get a weird namespace thing. If one of them is removed, everything is OK.

Has @georgringer an idea?

````
Fatal error: Uncaught exception 'TYPO3\CMS\Extbase\Object\Container\Exception\UnknownObjectException' with message 'Could not analyse class:Ecodev\News\Controller\NewsController maybe not loaded or no autoloader?' in /var/www/web23/html/TYPO3.CMS/typo3/sysext/extbase/Classes/Object/Container/ClassInfoFactory.php:37 Stack trace: #0 /var/www/web23/html/TYPO3.CMS/typo3/sysext/extbase/Classes/Object/Container/Container.php(315): TYPO3\CMS\Extbase\Object\Container\ClassInfoFactory->buildClassInfoFromClassName('Ecodev\\News\\Con...') #1 /var/www/web23/html/TYPO3.CMS/typo3/sysext/extbase/Classes/Object/Container/Container.php(157): TYPO3\CMS\Extbase\Object\Container\Container->getClassInfo('Ecodev\\News\\Con...') #2 /var/www/web23/html/TYPO3.CMS/typo3/sysext/extbase/Classes/Object/Container/Container.php(108): TYPO3\CMS\Extbase\Object\Container\Container->getInstanceInternal('Ecodev\\News\\Con...', Array) #3 /var/www/web23/html/TYPO3.CMS/typo3/sysext/extbase/Classes/Object/ObjectManager.php(94): TYP in /var/www/web23/html/TYPO3.CMS/typo3/sysext/extbase/Classes/Object/Container/ClassInfoFactory.php on line 37
````
## The Problem

Ecodev\News\Controller\NewsController 

I doubt that Newsletter has a NewsController ... Perhaps it is a TYPO in any namespace declaration that leads to this?

## Multiple Searches

with phpstorm on different namespace declaration terms, did not bring up a TYPO issue.

## Versions running

* TYPO3 6.2.10-dev 500df0ded1fec59fa5293d337fe57251fd796095
* ext:newsletter a1491e9666409dd245efbaee8ca2b2d94063c1fa
* ext:news  fc90edde27b88df07875ee643c19711bd39d64b3 -> which is more or less old

**Comment by githubrsys** [comment]
## Weird stuff

      cat Cache/Data/cache_classes/ecodev_news_controller_newscontroller 

     /var/www/web23/html/typo3conf/ext/news/Classes/Controller/NewsController.php�Ecodev\News\Controller\NewsController
